version: '3.1'

services:

  wordpress:
    image: bitnami/wordpress
    restart: always
    ports:
      - 8081:8080
    environment:
      WORDPRESS_DATABASE_HOST: mysqldb
      WORDPRESS_DATABASE_USER: exampleuser
      WORDPRESS_DATABASE_PASSWORD: examplepass
      WORDPRESS_DATABASE_NAME: exampledb
    volumes:
      - bitnami_wordpress_data:/bitnami/wordpress

  mysqldb:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - mysqldb_data:/var/lib/mysql

volumes:
  bitnami_wordpress_data:
  mysqldb_data:
